### ISSUE TITLE
NimaActor doesnt play on specific phone

### ISSUE THREAD

**Issue by taliptako** [2d-inc/Nima-Flutter#13]
Actually, i don't have any logs but my NimaActor just working in an Android Emulator but when I install the same app to my Mi 5 phone it doesn't play. I'm using this btw [https://github.com/2d-inc/HistoryOfEverything/tree/master/app/assets/Recorded_history](https://github.com/2d-inc/HistoryOfEverything/tree/master/app/assets/Recorded_history)
It just has a candle burning effect and this works in an Android Emulator but on my phone, it shows up but without animation that burning animation...
I just wonder if you have any idea why this not works on my phone. I didn't check the logs but i cant check if you need too..
```
NimaActor("assets/nima/Recorded_history.nma",
            fit: BoxFit.scaleDown, animation: "Untitled")
```

**Comment by taliptako** [comment]
Okay i get the logs
```
I/flutter (27383): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (27383): The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter (27383): The method 'advance' was called on null.
I/flutter (27383): Receiver: null
I/flutter (27383): Tried calling: advance()
I/flutter (27383): 
I/flutter (27383): When the exception was thrown, this was the stack:
I/flutter (27383): #0      NimaActorRenderObject._advance (package:nima/nima_actor.dart:334)
I/flutter (27383): #1      NimaActorRenderObject._beginFrame (package:nima/nima_actor.dart:277)
I/flutter (27383): #2      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012)
I/flutter (27383): #3      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:928)
I/flutter (27383): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367)
I/flutter (27383): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:926)
I/flutter (27383): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:856)
I/flutter (27383): #10     _invoke1 (dart:ui/hooks.dart:233)
I/flutter (27383): #11     _beginFrame (dart:ui/hooks.dart:172)
I/flutter (27383): (elided 3 frames from package dart:async)

```

**Comment by Fethi1** [comment]
i'm facing the same problem but mine the animation work sometimes and other doesn't, when it stopped i restart the app many times till it start playing again, tried release and it didn't work at all

**Comment by taliptako** [comment]
@luigi-rosso Do you still maintain nima repo ?

**Comment by niladri-paul** [comment]
I am facing the same issue. Please help

**Comment by JosephSaw** [comment]
I am also having this issue, on my emulator and the physical device. NimaFlutter is basically unusable like this
